config/routes.rb
Hitobito::Application.routes.draw do

  extend LanguageRouteScope

  root to: 'dashboard#index'

  get '/healthz', to: 'healthz#show'
  get '/healthz/mail', to: 'healthz/mail#show'

  language_scope do

    get '/404', to: 'errors#404'
    get '/500', to: 'errors#500'
    get '/503', to: 'errors#503'

    get '/people/query' => 'person/query#index', as: :query_people
    get '/people/company_name' => 'person/company_name#index', as: :query_company_name
    get '/people/:id' => 'person/top#show', as: :person
    get '/events/:id' => 'event/top#show', as: :event

    resources :groups do
      member do
        get :deleted_subgroups
        get :export_subgroups
        post :reactivate

        get 'merge' => 'group/merge#select'
        post 'merge' => 'group/merge#perform'

        get 'move' => 'group/move#select'
        post 'move' => 'group/move#perform'

      end

      resource :invoice_list, except: [:edit]
      resource :invoice_config, only: [:edit, :show, :update]

      resources :invoices do
        resources :payments, only: :create
      end
      resources :invoice_articles

      resource :payment_process, only: [:new, :show, :create]
      resources :notes, only: [:index, :create, :destroy]

      resources :people, except: [:new, :create] do

        member do
          post :send_password_instructions
          put :primary_group

          get 'history' => 'person/history#index'
          get 'log' => 'person/log#index'
          get 'colleagues' => 'person/colleagues#index'
          get 'invoices' => 'person/invoices#index'
        end

        resources :notes, only: [:create, :destroy]
        resources :qualifications, only: [:new, :create, :destroy]
        get 'qualifications' => 'qualifications#new' # route required for language switch

        scope module: 'person' do
          post 'tags' => 'tags#create'
          delete 'tags' => 'tags#destroy'
          get 'tags/query' => 'tags#query'
          post 'impersonate' => 'impersonation#create'
          delete 'impersonate' => 'impersonation#destroy'
          get 'households' => 'households#new'
        end

      end

      resource :role_list, only: [:destroy, :create, :new] do
        get 'deletable' => 'role_lists#deletable'
        get 'move'      => 'role_lists#move'
        get 'movable'   => 'role_lists#movable'
        put 'move'      => 'role_lists#update'
      end
      resources :roles, except: [:index, :show] do
        collection do
          get :details
          get :role_types
        end
      end
      get 'roles' => 'roles#new' # route required for language switch
      get 'roles/:id' => 'roles#edit' # route required for language switch

      resources :people_filters, only: [:new, :create, :edit, :update, :destroy]
      get 'people_filters' => 'people_filters#new' # route required for language switch

      get 'deleted_people' => 'group/deleted_people#index'

      get 'person_add_requests' => 'group/person_add_requests#index', as: :person_add_requests
      post 'person_add_requests' => 'group/person_add_requests#activate'
      delete 'person_add_requests' => 'group/person_add_requests#deactivate'

      put 'person_add_request_ignored_approvers' =>
            'group/person_add_request_ignored_approvers#update',
          as: 'person_add_request_ignored_approvers'

      get 'public_events/:id' => 'public_events#show', as: :public_event
      get 'events/participation_lists/new' => 'event/participation_lists#new'

      resources :events do
        collection do
          get 'simple' => 'events#index'
          get 'course' => 'events#index', type: 'Event::Course'
          get 'typeahead' => 'events#typeahead'
        end

        scope module: 'event' do

          member do
            get  'register' => 'register#index'
            post 'register' => 'register#check'
            put  'register' => 'register#register'
          end

          resources :application_market, only: :index do
            member do
              put    'waiting_list' => 'application_market#put_on_waiting_list'
              delete 'waiting_list' => 'application_market#remove_from_waiting_list'
              put    'participant' => 'application_market#add_participant'
              delete 'participant' => 'application_market#remove_participant'
            end
          end

          resources :applications, only: [] do
            member do
              put    :approve
              delete :reject
            end
          end

          resources :attachments, only: [:create, :destroy]

          resource :participation_lists, only: :create
          resources :participations do
            collection do
              get 'contact_data', controller: 'participation_contact_datas', action: 'edit'
              post 'contact_data', controller: 'participation_contact_datas', action: 'update'
            end
            member do
              get 'print'
            end
          end

          resources :roles, except: [:index, :show]
          get 'roles' => 'roles#new' # route required for language switch
          get 'roles/:id' => 'roles#edit' # route required for language switch

          get 'qualifications' => 'qualifications#index'
          put 'qualifications' => 'qualifications#update'
        end

      end

      resources :mailing_lists do
        resources :subscriptions, only: [:index, :destroy] do
          collection do
            resources :person, only: [:new, :create], controller: 'subscriber/person'
            get 'person' => 'subscriber/person#new' # route required for language switch

            resources :exclude_person, only: [:new, :create], controller: 'subscriber/exclude_person'
            get 'exclude_person' => 'subscriber/exclude_person#new' # route required for language switch

            resources :group, only: [:new, :create], controller: 'subscriber/group' do
              collection do
                get :query
                get :roles
              end
            end
            get 'group' => 'subscriber/group#new' # route required for language switch

            resources :event, only: [:new, :create], controller: 'subscriber/event' do
              collection do
                get :query
              end
            end
            get 'event' => 'subscriber/event#new' # route required for language switch

            resource :user, only: [:create, :destroy], controller: 'subscriber/user'
          end
        end

        resources :mailchimp_synchronizations, only: [:create]
      end

      resource :csv_imports, only: [:new, :create], controller: 'person/csv_imports' do
        member do
          post :define_mapping
          post :preview
          get 'define_mapping' => 'person/csv_imports#new' # route required for language switch
          get 'preview'        => 'person/csv_imports#new' # route required for language switch
        end
      end

      resources :service_tokens

    end # resources :group

    get 'list_courses' => 'event/lists#courses', as: :list_courses
    get 'list_events' => 'event/lists#events', as: :list_events

    get 'full' => 'full_text#index'
    get 'query' => 'full_text#query'

    resources :event_kinds, module: 'event', controller: 'kinds'

    resources :qualification_kinds

    resources :label_formats do
      collection do
        resource :settings, controller: 'label_format/settings', as: 'label_format_settings'
      end
    end

    resources :custom_contents, only: [:index, :edit, :update]
    get 'custom_contents/:id' => 'custom_contents#edit'

    devise_for :service_tokens, only: [:sessions]
    devise_for :people, skip: [:registrations], path: "users"
    as :person do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_person_registration'
      put 'users' => 'devise/registrations#update', :as => 'person_registration'
      get 'users' => 'devise/registrations#edit' # route required for language switch

      post 'users/token' => 'devise/tokens#create'
      delete 'users/token' => 'devise/tokens#destroy'
    end

    post 'person_add_requests/:id' => 'person/add_requests#approve', as: :person_add_request
    delete 'person_add_requests/:id' => 'person/add_requests#reject'

    get 'changelog' => 'changelog#index'

    get 'downloads/:id' => 'async_downloads#show'
    get 'downloads/:id/exists' => 'async_downloads#exists?'

    get 'synchronizations/:id' => 'async_synchronizations#show'

  end # scope locale

end

app/models/event/answer.rb
# encoding: utf-8

#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.
# == Schema Information
#
# Table name: event_answers
#
#  id               :integer          not null, primary key
#  participation_id :integer          not null
#  question_id      :integer          not null
#  answer           :string(255)
#

class Event::Answer < ActiveRecord::Base

  attr_writer :answer_required

  delegate :admin?, to: :question

  belongs_to :participation
  belongs_to :question


  validates_by_schema
  validates :question_id, uniqueness: { scope: :participation_id }
  validates :answer, presence: { if: lambda do
    question && question.required? && participation.enforce_required_answers
  end }
  validate :assert_answer_is_in_choice_items

  # override to handle array values submitted from checkboxes
  def answer=(text)
    if question_with_choices? && question.multiple_choices? && text.is_a?(Array)
      valid_range = (0...question.choice_items.size)
      # have submit index + 1 and handle reset via index 0
      index_array = text.map(&:to_i).map { |i| i - 1 }

      super(valid_index_based_values(index_array, valid_range) || nil)
    else
      super
    end
  end

  private

  def assert_answer_is_in_choice_items
    # still allow answer to be nil because otherwise participations could not
    # be created without answering all questions (required to create roles for other people)
    if question_with_choices? &&
       answer &&
       !question.multiple_choices? &&
       !question.choice_items.include?(answer)
      errors.add(:answer, :inclusion)
    end
  end

  def question_with_choices?
    question && question.choice_items.present?
  end

  def valid_index_based_values(index_array, valid_range)
    indexes = index_array.map do |index|
      if valid_range.include?(index)
        question.choice_items[index]
      end
    end.compact

    indexes.present? ? indexes.join(', ') : nil
  end
end

app/models/event/application.rb
# encoding: utf-8

#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.
# == Schema Information
#
# Table name: event_applications
#
#  id                   :integer          not null, primary key
#  priority_1_id        :integer          not null
#  priority_2_id        :integer
#  priority_3_id        :integer
#  approved             :boolean          default(FALSE), not null
#  rejected             :boolean          default(FALSE), not null
#  waiting_list         :boolean          default(FALSE), not null
#  waiting_list_comment :text(65535)
#

class Event::Application < ActiveRecord::Base

  self.demodulized_route_keys = true

  ### ASSOCIATION

  # dependent: :nullify not working with rails 4.2.3, uncomment later
  has_one :participation, inverse_of: :application # , dependent: :nullify

  has_one :event, through: :participation

  belongs_to :priority_1, class_name: 'Event' #::Course
  belongs_to :priority_2, class_name: 'Event' #::Course
  belongs_to :priority_3, class_name: 'Event' #::Course


  validates_by_schema

  ### CLASS METHODS

  class << self
    def pending
      joins(:participation).
        where(event_participations: { active: false },
              rejected: false)
    end

    def label(args = {})
      model_name.human(args)
    end

    def label_plural
      model_name.human(count: 2)
    end
  end

  ### INSTANCE METHODS

  delegate :contact, to: :event

  def priority(event)
    [1, 2, 3].detect { |i| send("priority_#{i}_id") == event.id }
  end
end

app/models/event/attachment.rb
# encoding: utf-8

#  Copyright (c) 2015, Pro Natura Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.
# == Schema Information
#
# Table name: event_attachments
#
#  id       :integer          not null, primary key
#  event_id :integer          not null
#  file     :string(255)      not null
#

class Event::Attachment < ActiveRecord::Base

  MAX_FILE_SIZE = Settings.event.attachments.max_file_size.megabytes

  belongs_to :event

  mount_uploader :file, Event::AttachmentUploader

  validates_by_schema except: :file
  validate :assert_file_size

  scope :list, -> { order(:file) }

  def to_s
    file
  end

  private

  def assert_file_size
    if file.size.to_f > MAX_FILE_SIZE
      errors.add(:file, :filesize_too_large, maximum: MAX_FILE_SIZE / 1.megabyte)
    end
  end

end

app/models/event/attachment_uploader.rb
# encoding: utf-8

#  Copyright (c) 2015, Pro Natura Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

class Event::AttachmentUploader < Uploader::Base

  self.allowed_extensions = Settings.event.attachments.file_extensions.split(/\s+/)

end

app/models/event/course.rb
# encoding: utf-8

#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.
# == Schema Information
#
# Table name: events
#
#  id                          :integer          not null, primary key
#  type                        :string(255)
#  name                        :string(255)      not null
#  number                      :string(255)
#  motto                       :string(255)
#  cost                        :string(255)
#  maximum_participants        :integer
#  contact_id                  :integer
#  description                 :text(65535)
#  location                    :text(65535)
#  application_opening_at      :date
#  application_closing_at      :date
#  application_conditions      :text(65535)
#  kind_id                     :integer
#  state                       :string(60)
#  priorization                :boolean          default(FALSE), not null
#  requires_approval           :boolean          default(FALSE), not null
#  created_at                  :datetime
#  updated_at                  :datetime
#  participant_count           :integer          default(0)
#  application_contact_id      :integer
#  external_applications       :boolean          default(FALSE)
#  applicant_count             :integer          default(0)
#  teamer_count                :integer          default(0)
#  signature                   :boolean
#  signature_confirmation      :boolean
#  signature_confirmation_text :string(255)
#  creator_id                  :integer
#  updater_id                  :integer
#  applications_cancelable     :boolean          default(FALSE), not null
#  required_contact_attrs      :text(65535)
#  hidden_contact_attrs        :text(65535)
#  display_booking_info        :boolean          default(TRUE), not null
#

class Event::Course < Event

  # This statement is required because this class would not be loaded otherwise.
  require_dependency 'event/course/role/participant'

  self.used_attributes += [:number, :kind_id, :state, :priorization, :group_ids,
                           :requires_approval, :display_booking_info]

  self.role_types = [Event::Role::Leader,
                     Event::Role::AssistantLeader,
                     Event::Role::Cook,
                     Event::Role::Helper,
                     Event::Role::Treasurer,
                     Event::Role::Speaker,
                     Event::Course::Role::Participant]

  self.supports_applications = true

  self.kind_class = Event::Kind


  belongs_to :kind

  validates :kind_id, presence: true, if: -> { used_attributes.include?(:kind_id) }


  def label_detail
    label = used_attributes.include?(:kind_id) ? "#{kind.short_name} " : ''
    label << "#{number} #{group_names}"
  end

  # Does this event provide qualifications
  def qualifying?
    kind_id? && kind.qualifying?
  end

  # The date on which qualification obtained in this course start
  def qualification_date
    @qualification_date ||= begin
      last = dates.reorder('event_dates.start_at DESC').first
      last.finish_at || last.start_at
    end.to_date
  end

  def start_date
    @start_date ||= dates.first.start_at.to_date
  end

  def init_questions
    if application_questions.blank?
      Event::Question.application.global.each do |q|
        application_questions << q.dup
      end
    end
  end

end

app/views/event/application_market/_application.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

%tr{id: dom_id(p)}
  %td
    = link_to(icon('arrow-left'),
              participant_group_event_application_market_path(@group, @event, p),
              remote: true,
              method: :put)

  = render 'participation', p: p

  %td
    = render 'waiting_list_link', p: p

app/views/event/application_market/_participant.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

%tr{id: dom_id(p)}
  = render 'participation', p: p

  %td
    = link_to(icon('arrow-right'),
              participant_group_event_application_market_path(@group, @event, p),
              remote: true,
              method: :delete)

app/views/event/application_market/_participation.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

%td
  %strong= link_to(p.to_s(:list), group_event_participation_path(@group, @event, p.id))
  %br/
  = p.person_location_information
  %br/
  .muted
    = t('.registered_at', date: f(p.created_at.to_date))

%td= p.application.priority(event)
%td= p.application.precondition_warnings(event)
%td= p.application.approval_badge if event.requires_approval?

app/views/event/application_market/_popover_waiting_list.html.haml
- #  Copyright (c) 2012-2015, Pfadibewegung Schweiz. This file is part of
- #  hitobito and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito.

%p.muted= t('.waiting_list_info', event_kind: @event.kind)
%br/

= standard_form(p.application,
                url: waiting_list_group_event_application_market_path(@group, @event, p.id),
                method: :put,
                remote: true,
                stacked: true) do |f|
  = f.labeled_input_field(:waiting_list_comment, class: 'span12')
  = save_form_buttons(f, nil, '#')

app/views/event/application_market/_prio_buttons.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

= form_tag nil, class: 'form-inline', style: 'margin-bottom: 10px;', method: :get do
  .btn-group{data_toggle: 'buttons-checkbox'}
    = render 'prio_check', prio: 1
    = render 'prio_check', prio: 2
    = render 'prio_check', prio: 3
    %label.checkbox
      = check_box_tag :waiting_list, true, params[:waiting_list]
      = t('.national_waitinglist')

  = submit_tag t('global.button.refresh'), class: 'btn btn-small'

app/views/event/application_market/_prio_check.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

%label.checkbox
  = check_box_tag 'prio[]', prio, params[:prio] && params[:prio].include?(prio.to_s)
  = "Prio #{prio}" 

app/views/event/application_market/_waiting_list_link.html.haml
- if p.application
  - if p.application.waiting_list?
    = link_to("#{icon('ok')}&nbsp; #{t('.label')}".html_safe,
              waiting_list_group_event_application_market_path(@group, @event, p.id),
              title: t('.title_active'),
              remote: true,
              method: :delete)
    - if p.application.waiting_list_comment?
      &nbsp;
      = badge(icon('comment', class: 'icon-white'), 'info', simple_format(p.application.waiting_list_comment))

  - else
    .popover-small
      = link_to("#{icon('minus')}&nbsp; #{t('.label')}".html_safe,
                '#',
                title: t('.title_inactive'),
                data: { toggle: 'popover',
                        content: render('popover_waiting_list', p: p).to_str })

app/views/event/application_market/add_participant.js.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

handler = new App.ApplicationMarket()

handler.moveElementToBottom('#{dom_id(@participation)}', 'participants', function() {
$('##{dom_id(@participation)}').remove();
$('#participants').append('#{j(render('participant', p: @participation))}');
handler.updateCount();
});
$('#booking_info').html('#{j(event.booking_info)}');
$('#active_participants_info').html('#{j(event.active_participants_info)}');

app/views/event/application_market/index.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

-title event.to_s

.row-fluid
  .btn-toolbar.span9
    - if can?(:new, @event.participations.new)
      = Dropdown::Event::ParticipantAdd.new(self,
                                            @group,
                                            @event,
                                            t('.add_participant'),
                                            :plus,
                                            for_someone_else: true)

  .span3
    %span#booking_info= event.booking_info

#main.row-fluid
  %article.span6
    %h2= t('.assigned_participants')
    %p{style: 'padding-top: 7px; margin-bottom: 25px;'}
      %span#active_participants_info= event.active_participants_info

    %div{style: "max-width: 550px;"}
      %table.table.table-striped.table-hover
        %tbody#participants
          - @participants.each do |p|
            = render 'participant', p: p


  %article.span6
    %h2= Event::Application.label_plural
    .pending_applications_info
      %span= "#{@applications.count} #{Event::Application.label(count: @applications.count)}"
      %span.hidden.one=Event::Application.label
      %span.hidden.other=Event::Application.label_plural

    = render 'prio_buttons'

    %div{style: "max-width: 600px;"}
      %table.table.table-striped.table-hover
        %tbody#applications
          - @applications.each do |p|
            = render 'application', p: p

app/views/event/application_market/participation_exists_error.js.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

alert('#{t(:"event.application_market.already_assigned")}');

app/views/event/application_market/remove_participant.js.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

handler = new App.ApplicationMarket()
handler.moveElementToBottom('#{dom_id(@participation)}', 'applications', function() {
$('##{dom_id(@participation)}').remove();
$('#applications').append('#{j(render('application', p: @participation))}');
handler.updateCount();
});
$('#booking_info').html('#{j(event.booking_info)}');
$('#active_participants_info').html('#{j(event.active_participants_info)}');

app/views/event/application_market/waiting_list.js.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

$('##{dom_id(@participation)} td:last').html('#{escape_javascript(render('waiting_list_link', p: @participation))}')