config/routes.rb
Hitobito::Application.routes.draw do

  extend LanguageRouteScope

  root to: 'dashboard#index'

  get '/healthz', to: 'healthz#show'
  get '/healthz/mail', to: 'healthz/mail#show'

  language_scope do

    get '/404', to: 'errors#404'
    get '/500', to: 'errors#500'
    get '/503', to: 'errors#503'

    get '/people/query' => 'person/query#index', as: :query_people
    get '/people/company_name' => 'person/company_name#index', as: :query_company_name
    get '/people/:id' => 'person/top#show', as: :person
    get '/events/:id' => 'event/top#show', as: :event

    resources :groups do
      member do
        get :deleted_subgroups
        get :export_subgroups
        post :reactivate

        get 'merge' => 'group/merge#select'
        post 'merge' => 'group/merge#perform'

        get 'move' => 'group/move#select'
        post 'move' => 'group/move#perform'

      end

      resource :invoice_list, except: [:edit]
      resource :invoice_config, only: [:edit, :show, :update]

      resources :invoices do
        resources :payments, only: :create
      end
      resources :invoice_articles

      resource :payment_process, only: [:new, :show, :create]
      resources :notes, only: [:index, :create, :destroy]

      resources :people, except: [:new, :create] do

        member do
          post :send_password_instructions
          put :primary_group

          get 'history' => 'person/history#index'
          get 'log' => 'person/log#index'
          get 'colleagues' => 'person/colleagues#index'
          get 'invoices' => 'person/invoices#index'
        end

        resources :notes, only: [:create, :destroy]
        resources :qualifications, only: [:new, :create, :destroy]
        get 'qualifications' => 'qualifications#new' # route required for language switch

        scope module: 'person' do
          post 'tags' => 'tags#create'
          delete 'tags' => 'tags#destroy'
          get 'tags/query' => 'tags#query'
          post 'impersonate' => 'impersonation#create'
          delete 'impersonate' => 'impersonation#destroy'
          get 'households' => 'households#new'
        end

      end

      resource :role_list, only: [:destroy, :create, :new] do
        get 'deletable' => 'role_lists#deletable'
        get 'move'      => 'role_lists#move'
        get 'movable'   => 'role_lists#movable'
        put 'move'      => 'role_lists#update'
      end
      resources :roles, except: [:index, :show] do
        collection do
          get :details
          get :role_types
        end
      end
      get 'roles' => 'roles#new' # route required for language switch
      get 'roles/:id' => 'roles#edit' # route required for language switch

      resources :people_filters, only: [:new, :create, :edit, :update, :destroy]
      get 'people_filters' => 'people_filters#new' # route required for language switch

      get 'deleted_people' => 'group/deleted_people#index'

      get 'person_add_requests' => 'group/person_add_requests#index', as: :person_add_requests
      post 'person_add_requests' => 'group/person_add_requests#activate'
      delete 'person_add_requests' => 'group/person_add_requests#deactivate'

      put 'person_add_request_ignored_approvers' =>
            'group/person_add_request_ignored_approvers#update',
          as: 'person_add_request_ignored_approvers'

      get 'public_events/:id' => 'public_events#show', as: :public_event
      get 'events/participation_lists/new' => 'event/participation_lists#new'

      resources :events do
        collection do
          get 'simple' => 'events#index'
          get 'course' => 'events#index', type: 'Event::Course'
          get 'typeahead' => 'events#typeahead'
        end

        scope module: 'event' do

          member do
            get  'register' => 'register#index'
            post 'register' => 'register#check'
            put  'register' => 'register#register'
          end

          resources :application_market, only: :index do
            member do
              put    'waiting_list' => 'application_market#put_on_waiting_list'
              delete 'waiting_list' => 'application_market#remove_from_waiting_list'
              put    'participant' => 'application_market#add_participant'
              delete 'participant' => 'application_market#remove_participant'
            end
          end

          resources :applications, only: [] do
            member do
              put    :approve
              delete :reject
            end
          end

          resources :attachments, only: [:create, :destroy]

          resource :participation_lists, only: :create
          resources :participations do
            collection do
              get 'contact_data', controller: 'participation_contact_datas', action: 'edit'
              post 'contact_data', controller: 'participation_contact_datas', action: 'update'
            end
            member do
              get 'print'
            end
          end

          resources :roles, except: [:index, :show]
          get 'roles' => 'roles#new' # route required for language switch
          get 'roles/:id' => 'roles#edit' # route required for language switch

          get 'qualifications' => 'qualifications#index'
          put 'qualifications' => 'qualifications#update'
        end

      end

      resources :mailing_lists do
        resources :subscriptions, only: [:index, :destroy] do
          collection do
            resources :person, only: [:new, :create], controller: 'subscriber/person'
            get 'person' => 'subscriber/person#new' # route required for language switch

            resources :exclude_person, only: [:new, :create], controller: 'subscriber/exclude_person'
            get 'exclude_person' => 'subscriber/exclude_person#new' # route required for language switch

            resources :group, only: [:new, :create], controller: 'subscriber/group' do
              collection do
                get :query
                get :roles
              end
            end
            get 'group' => 'subscriber/group#new' # route required for language switch

            resources :event, only: [:new, :create], controller: 'subscriber/event' do
              collection do
                get :query
              end
            end
            get 'event' => 'subscriber/event#new' # route required for language switch

            resource :user, only: [:create, :destroy], controller: 'subscriber/user'
          end
        end

        resources :mailchimp_synchronizations, only: [:create]
      end

      resource :csv_imports, only: [:new, :create], controller: 'person/csv_imports' do
        member do
          post :define_mapping
          post :preview
          get 'define_mapping' => 'person/csv_imports#new' # route required for language switch
          get 'preview'        => 'person/csv_imports#new' # route required for language switch
        end
      end

      resources :service_tokens

    end # resources :group

    get 'list_courses' => 'event/lists#courses', as: :list_courses
    get 'list_events' => 'event/lists#events', as: :list_events

    get 'full' => 'full_text#index'
    get 'query' => 'full_text#query'

    resources :event_kinds, module: 'event', controller: 'kinds'

    resources :qualification_kinds

    resources :label_formats do
      collection do
        resource :settings, controller: 'label_format/settings', as: 'label_format_settings'
      end
    end

    resources :custom_contents, only: [:index, :edit, :update]
    get 'custom_contents/:id' => 'custom_contents#edit'

    devise_for :service_tokens, only: [:sessions]
    devise_for :people, skip: [:registrations], path: "users"
    as :person do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_person_registration'
      put 'users' => 'devise/registrations#update', :as => 'person_registration'
      get 'users' => 'devise/registrations#edit' # route required for language switch

      post 'users/token' => 'devise/tokens#create'
      delete 'users/token' => 'devise/tokens#destroy'
    end

    post 'person_add_requests/:id' => 'person/add_requests#approve', as: :person_add_request
    delete 'person_add_requests/:id' => 'person/add_requests#reject'

    get 'changelog' => 'changelog#index'

    get 'downloads/:id' => 'async_downloads#show'
    get 'downloads/:id/exists' => 'async_downloads#exists?'

    get 'synchronizations/:id' => 'async_synchronizations#show'

  end # scope locale

end

app/models/note.rb
# encoding: utf-8

#  Copyright (c) 2012-2016, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.
# == Schema Information
#
# Table name: notes
#
#  id           :integer          not null, primary key
#  subject_id   :integer          not null
#  author_id    :integer          not null
#  text         :text(65535)
#  created_at   :datetime
#  updated_at   :datetime
#  subject_type :string(255)
#

class Note < ActiveRecord::Base

  ### ASSOCIATIONS

  belongs_to :subject, polymorphic: true
  belongs_to :author, class_name: 'Person'

  ### VALIDATIONS

  validates_by_schema
  validates :text, presence: true

  scope :list, -> { order(created_at: :desc) }

  class << self
    def in_or_layer_below(group)
      joins('LEFT JOIN roles ' \
            "ON roles.person_id = notes.subject_id AND notes.subject_type = '#{Person.sti_name}'").
        joins('INNER JOIN groups ' \
              "ON (groups.id = notes.subject_id AND notes.subject_type = '#{Group.sti_name}') " \
              'OR (groups.id = roles.group_id)').
        where(roles: { deleted_at: nil },
              groups: { deleted_at: nil, layer_group_id: group.layer_group_id }).
        where('groups.lft >= :lft AND groups.rgt <= :rgt', lft: group.lft, rgt: group.rgt).
        uniq
    end
  end

  def to_s
    text.to_s.delete("\n").truncate(10)
  end

end

app/controllers/notes_controller.rb
# encoding: utf-8

#  Copyright (c) 2012-2017, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

class NotesController < ApplicationController

  decorates :group, :person

  def index
    authorize!(:index_notes, group)
    @notes = entries
  end

  def create
    @note = subject.notes.build(permitted_params.merge(author_id: current_user.id))
    authorize!(:create, @note)
    @note.save

    respond_to do |format|
      format.html { redirect_to subject_path }
      format.js { group } # create.js.haml
    end
  end

  def destroy
    @note = Note.find(params[:id])
    authorize!(:destroy, @note)
    @note.destroy

    respond_to do |format|
      format.html { redirect_to subject_path }
      format.js # destroy.js.haml
    end
  end

  private

  def entries
    Note
      .includes(:subject, :author)
      .in_or_layer_below(group)
      .list
      .page(params[:notes_page])
      .tap do |notes|
      Person::PreloadGroups.for(notes.collect(&:subject).select { |s| s.is_a?(Person) })
      Person::PreloadGroups.for(notes.collect(&:author))
    end
  end

  def group
    @group ||= Group.find(params[:group_id])
  end

  def subject
    if params[:person_id]
      Person.find(params[:person_id])
    else
      group
    end
  end

  def permitted_params
    params.require(:note).permit(:text)
  end

  def subject_path
    if @note.subject_type == Group.name
      group_path(id: group.id)
    else
      group_person_path(group_id: group.id, id: subject.id)
    end
  end

end

app/helpers/notes_helper.rb
# encoding: utf-8

#  Copyright (c) 2017, Dachverband Schweizer Jugendparlamente. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

module NotesHelper

  def note_path(group, note)
    if note.subject.is_a?(Group)
      group_note_path(group_id: note.subject_id, id: note.id)
    else
      group_person_note_path(group_id: group.id, person_id: note.subject_id, id: note.id)
    end
  end

end

app/views/notes/_list.html.haml
-#  Copyright (c) 2012-2016, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

.pagination-bar
  = render 'notes/paginator', notes: notes

#notes-list
  - if notes.total_count == 0
    .pagination-info
      = ti(:no_list_entries)

  - notes.each do |note|
    = render note, show_subject: show_subject

= render 'notes/paginator', notes: notes

app/views/notes/_note.html.haml
-#  Copyright (c) 2012-2016, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

.row-fluid.note{id: dom_id(note), class: ('is-current-subject' unless show_subject)}
  - if show_subject
    .note-image
      - case note.subject
      - when Group
        = image_tag('group.svg')
      - when Person
        %img{src: note.subject.picture}

  .note-body
    - if show_subject
      = assoc_link(note.subject)

    %small.muted.note-author
      = person_link(note.author)
      .note-date
        = t('.created', time_ago: time_ago_in_words(note.created_at))
      - if can?(:destroy, note)
        = link_to icon(:trash),
                  note_path(@group, note),
                  method: :delete,
                  remote: true,
                  data: { confirm: ti(:confirm_delete) }

    = auto_link(simple_format(note.text))

app/views/notes/_paginator.html.haml
-#  Copyright (c) 2012-2017, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

- if notes.total_pages > 1
  .pagination.notes-pagination
    %ul
      %li{class: notes.first_page? && :disabled}
        = link_to_previous_page notes,
                                t('views.pagination.previous'),
                                param_name: :notes_page,
                                params: { anchor: 'notes' }
        - if notes.first_page?
          %a= t('views.pagination.previous')
      %li{class: notes.last_page? && :disabled}
        = link_to_next_page notes,
                            t('views.pagination.next'),
                            param_name: :notes_page,
                            params: { anchor: 'notes' }
        - if notes.last_page?
          %a= t('views.pagination.next')

app/views/notes/_section.html.haml
-#  Copyright (c) 2012-2017, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.


%section
  %h2
    = Note.model_name.human(count: 2)
    - if can?(:create, entry.notes.new)
      %span.pull-right
        = action_button(t('notes.new_note'),
                        '#',
                        'plus',
                        id: 'notes-new-button',
                        class: 'btn-small notes-swap',
                        data: { swap: 'notes-swap' })

  #notes-form.notes-swap{ style: 'display: none;', data: { swap: 'notes-swap' } }
    #notes-error.alert.alert-error{ style: 'display: none;' }

    = form_for(Note.new, url: create_path, remote: true) do |f|
      = f.text_area(:text, rows: 5, class: 'input-block-level')
      = save_form_buttons(f, nil, '')

  = render 'notes/list',
           notes: entry.notes.includes(:author, :subject).list.page(params[:notes_page]).per(10),
           show_subject: false

app/views/notes/create.js.haml
-#  Copyright (c) 2012-2017, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

- if @note.errors.blank?
  App.Notes.addNote('#{escape_javascript(render @note, show_subject: false)}');
- else
  App.Notes.showError('#{@note.errors.full_messages.join("\n")}');

app/views/notes/destroy.js.haml
-#  Copyright (c) 2012-2016, hitobito AG. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

- if @note.destroyed?
  $('#notes-list ##{dom_id(@note)}').remove()
- else
  alert('#{t('.failure', errors: @note.errors.full_messages.join(', '))}');

app/views/notes/index.html.haml
-#  Copyright (c) 2012-2016, Dachverband Schweizer Jugendparlamente. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

- @sheet = Sheet::Group.new(self)

#notes-index
  = render 'list', notes: @notes, show_subject: true