config/routes.rb
Hitobito::Application.routes.draw do

  extend LanguageRouteScope

  root to: 'dashboard#index'

  get '/healthz', to: 'healthz#show'
  get '/healthz/mail', to: 'healthz/mail#show'

  language_scope do

    get '/404', to: 'errors#404'
    get '/500', to: 'errors#500'
    get '/503', to: 'errors#503'

    get '/people/query' => 'person/query#index', as: :query_people
    get '/people/company_name' => 'person/company_name#index', as: :query_company_name
    get '/people/:id' => 'person/top#show', as: :person
    get '/events/:id' => 'event/top#show', as: :event

    resources :groups do
      member do
        get :deleted_subgroups
        get :export_subgroups
        post :reactivate

        get 'merge' => 'group/merge#select'
        post 'merge' => 'group/merge#perform'

        get 'move' => 'group/move#select'
        post 'move' => 'group/move#perform'

      end

      resource :invoice_list, except: [:edit]
      resource :invoice_config, only: [:edit, :show, :update]

      resources :invoices do
        resources :payments, only: :create
      end
      resources :invoice_articles

      resource :payment_process, only: [:new, :show, :create]
      resources :notes, only: [:index, :create, :destroy]

      resources :people, except: [:new, :create] do

        member do
          post :send_password_instructions
          put :primary_group

          get 'history' => 'person/history#index'
          get 'log' => 'person/log#index'
          get 'colleagues' => 'person/colleagues#index'
          get 'invoices' => 'person/invoices#index'
        end

        resources :notes, only: [:create, :destroy]
        resources :qualifications, only: [:new, :create, :destroy]
        get 'qualifications' => 'qualifications#new' # route required for language switch

        scope module: 'person' do
          post 'tags' => 'tags#create'
          delete 'tags' => 'tags#destroy'
          get 'tags/query' => 'tags#query'
          post 'impersonate' => 'impersonation#create'
          delete 'impersonate' => 'impersonation#destroy'
          get 'households' => 'households#new'
        end

      end

      resource :role_list, only: [:destroy, :create, :new] do
        get 'deletable' => 'role_lists#deletable'
        get 'move'      => 'role_lists#move'
        get 'movable'   => 'role_lists#movable'
        put 'move'      => 'role_lists#update'
      end
      resources :roles, except: [:index, :show] do
        collection do
          get :details
          get :role_types
        end
      end
      get 'roles' => 'roles#new' # route required for language switch
      get 'roles/:id' => 'roles#edit' # route required for language switch

      resources :people_filters, only: [:new, :create, :edit, :update, :destroy]
      get 'people_filters' => 'people_filters#new' # route required for language switch

      get 'deleted_people' => 'group/deleted_people#index'

      get 'person_add_requests' => 'group/person_add_requests#index', as: :person_add_requests
      post 'person_add_requests' => 'group/person_add_requests#activate'
      delete 'person_add_requests' => 'group/person_add_requests#deactivate'

      put 'person_add_request_ignored_approvers' =>
            'group/person_add_request_ignored_approvers#update',
          as: 'person_add_request_ignored_approvers'

      get 'public_events/:id' => 'public_events#show', as: :public_event
      get 'events/participation_lists/new' => 'event/participation_lists#new'

      resources :events do
        collection do
          get 'simple' => 'events#index'
          get 'course' => 'events#index', type: 'Event::Course'
          get 'typeahead' => 'events#typeahead'
        end

        scope module: 'event' do

          member do
            get  'register' => 'register#index'
            post 'register' => 'register#check'
            put  'register' => 'register#register'
          end

          resources :application_market, only: :index do
            member do
              put    'waiting_list' => 'application_market#put_on_waiting_list'
              delete 'waiting_list' => 'application_market#remove_from_waiting_list'
              put    'participant' => 'application_market#add_participant'
              delete 'participant' => 'application_market#remove_participant'
            end
          end

          resources :applications, only: [] do
            member do
              put    :approve
              delete :reject
            end
          end

          resources :attachments, only: [:create, :destroy]

          resource :participation_lists, only: :create
          resources :participations do
            collection do
              get 'contact_data', controller: 'participation_contact_datas', action: 'edit'
              post 'contact_data', controller: 'participation_contact_datas', action: 'update'
            end
            member do
              get 'print'
            end
          end

          resources :roles, except: [:index, :show]
          get 'roles' => 'roles#new' # route required for language switch
          get 'roles/:id' => 'roles#edit' # route required for language switch

          get 'qualifications' => 'qualifications#index'
          put 'qualifications' => 'qualifications#update'
        end

      end

      resources :mailing_lists do
        resources :subscriptions, only: [:index, :destroy] do
          collection do
            resources :person, only: [:new, :create], controller: 'subscriber/person'
            get 'person' => 'subscriber/person#new' # route required for language switch

            resources :exclude_person, only: [:new, :create], controller: 'subscriber/exclude_person'
            get 'exclude_person' => 'subscriber/exclude_person#new' # route required for language switch

            resources :group, only: [:new, :create], controller: 'subscriber/group' do
              collection do
                get :query
                get :roles
              end
            end
            get 'group' => 'subscriber/group#new' # route required for language switch

            resources :event, only: [:new, :create], controller: 'subscriber/event' do
              collection do
                get :query
              end
            end
            get 'event' => 'subscriber/event#new' # route required for language switch

            resource :user, only: [:create, :destroy], controller: 'subscriber/user'
          end
        end

        resources :mailchimp_synchronizations, only: [:create]
      end

      resource :csv_imports, only: [:new, :create], controller: 'person/csv_imports' do
        member do
          post :define_mapping
          post :preview
          get 'define_mapping' => 'person/csv_imports#new' # route required for language switch
          get 'preview'        => 'person/csv_imports#new' # route required for language switch
        end
      end

      resources :service_tokens

    end # resources :group

    get 'list_courses' => 'event/lists#courses', as: :list_courses
    get 'list_events' => 'event/lists#events', as: :list_events

    get 'full' => 'full_text#index'
    get 'query' => 'full_text#query'

    resources :event_kinds, module: 'event', controller: 'kinds'

    resources :qualification_kinds

    resources :label_formats do
      collection do
        resource :settings, controller: 'label_format/settings', as: 'label_format_settings'
      end
    end

    resources :custom_contents, only: [:index, :edit, :update]
    get 'custom_contents/:id' => 'custom_contents#edit'

    devise_for :service_tokens, only: [:sessions]
    devise_for :people, skip: [:registrations], path: "users"
    as :person do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_person_registration'
      put 'users' => 'devise/registrations#update', :as => 'person_registration'
      get 'users' => 'devise/registrations#edit' # route required for language switch

      post 'users/token' => 'devise/tokens#create'
      delete 'users/token' => 'devise/tokens#destroy'
    end

    post 'person_add_requests/:id' => 'person/add_requests#approve', as: :person_add_request
    delete 'person_add_requests/:id' => 'person/add_requests#reject'

    get 'changelog' => 'changelog#index'

    get 'downloads/:id' => 'async_downloads#show'
    get 'downloads/:id/exists' => 'async_downloads#exists?'

    get 'synchronizations/:id' => 'async_synchronizations#show'

  end # scope locale

end

app/controllers/people_controller.rb
# encoding: utf-8

#  Copyright (c) 2012-2018, Jungwacht Blauring Schweiz. This file is part of
#  hitobito and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

class PeopleController < CrudController

  include Concerns::RenderPeopleExports
  include Concerns::AsyncDownload

  self.nesting = Group

  self.remember_params += [:name, :range, :filters, :filter_id]

  self.permitted_attrs = [:first_name, :last_name, :company_name, :nickname, :company,
                          :gender, :birthday, :additional_information,
                          :picture, :remove_picture] +
                          Contactable::ACCESSIBLE_ATTRS +
                          [household_people_ids: []] +
                          [relations_to_tails_attributes: [:id, :tail_id, :kind, :_destroy]]



  # required to allow api calls
  protect_from_forgery with: :null_session, only: [:index, :show]


  decorates :group, :person, :people, :add_requests

  helper_method :index_full_ability?

  # load group before authorization
  prepend_before_action :parent

  prepend_before_action :entry, only: [:show, :edit, :update, :destroy,
                                       :send_password_instructions, :primary_group]

  before_save :validate_household
  after_save :persist_household

  before_render_show :load_person_add_requests, if: -> { html_request? }
  before_render_show :load_grouped_person_tags, if: -> { html_request? }
  before_render_index :load_people_add_requests, if: -> { html_request? }

  def index # rubocop:disable Metrics/AbcSize we support a lot of format, hence many code-branches
    respond_to do |format|
      format.html  { @people = prepare_entries(filter_entries).page(params[:page]) }
      format.pdf   { render_pdf(filter_entries, group) }
      format.csv   { render_tabular_entries_in_background(:csv)  && redirect_to(action: :index) }
      format.xlsx  { render_tabular_entries_in_background(:xlsx) && redirect_to(action: :index) }
      format.vcf   { render_vcf(filter_entries.includes(:phone_numbers)) }
      format.email { render_emails(filter_entries) }
      format.json  { render_entries_json(filter_entries) }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.pdf  { render_pdf([entry], group) }
      format.csv  { render_tabular_entry(:csv) }
      format.xlsx { render_tabular_entry(:xlsx) }
      format.vcf  { render_vcf([entry]) }
      format.json { render_entry_json }
    end
  end

  # POST button, send password instructions
  def send_password_instructions
    Person::SendLoginJob.new(entry, current_user).enqueue!
    notice = I18n.t("#{controller_name}.#{action_name}")
    respond_to do |format|
      format.html { redirect_to group_person_path(group, entry), notice: notice }
      format.js do
        flash.now.notice = notice
        render 'shared/update_flash'
      end
    end
  end

  # PUT button, ajax
  def primary_group
    entry.update!(primary_group_id: params[:primary_group_id])
    respond_to do |format|
      format.html { redirect_to group_person_path(group, entry) }
      format.js
    end
  end

  private_class_method

  # dont use class level accessor as expression is evaluated whenever constant is
  # loaded which might be before wagon that defines groups / roles has been loaded
  def self.sort_mappings_with_indifferent_access
    { roles: [Person.order_by_role_statement].
      concat(Person.order_by_name_statement) }.with_indifferent_access
  end

  private

  alias group parent

  def find_entry
    if group && group.root?
      # every person may be displayed underneath the root group,
      # even if it does not directly belong to it.
      Person.find(params[:id])
    else
      super
    end
  end

  def assign_attributes
    if model_params.present?
      email = model_params.delete(:email)
      entry.email = email if can?(:update_email, entry)
    end
    super
  end

  def load_people_add_requests
    if params[:range].blank? && can?(:create, @group.roles.new)
      @person_add_requests = @group.person_add_requests.list.includes(person: :primary_group)
    end
  end

  def load_person_add_requests
    if can?(:update, entry)
      @add_requests = entry.add_requests.includes(:body, requester: { roles: :group })
      set_add_request_status_notification if show_add_request_status?
    end
  end

  def load_grouped_person_tags
    @tags = entry.tags.grouped_by_category
  end

  def show_add_request_status?
    flash[:notice].blank? && flash[:alert].blank? &&
    params[:body_type].present? && params[:body_id].present?
  end

  def set_add_request_status_notification
    status = Person::AddRequest::Status.for(entry.id, params[:body_type], params[:body_id])
    return if status.pending?

    if status.created?
      flash.now[:notice] = status.approved_message
    else
      flash.now[:alert] = status.rejected_message
    end
  end

  def filter_entries
    entries = person_filter.entries
    entries = entries.reorder(sort_expression) if sorting?
    entries
  end

  def list_filter_args
    if params[:filter_id]
      PeopleFilter.for_group(group).find(params[:filter_id]).to_params
    else
      params
    end
  end

  def prepare_entries(entries)
    if index_full_ability?
      entries.includes(:additional_emails, :phone_numbers)
    else
      entries.preload_public_accounts
    end
  end

  def render_tabular_entries_in_background(format)
    full = params[:details].present? && index_full_ability?
    with_async_download_cookie(format, :people_export) do |filename|
      render_tabular_in_background(format, full, filename)
    end
  end

  def prepare_tabular_entries(entries, full)
    if full
      entries
        .select('people.*')
        .preload_accounts
        .includes(relations_to_tails: :tail, qualifications: { qualification_kind: :translations })
        .includes(:primary_group)
    else
      entries.preload_public_accounts.includes(:primary_group)
    end
  end

  def render_tabular_entry(format)
    render_tabular(format, [entry], params[:details].present? && can?(:show_full, entry))
  end

  def render_tabular_in_background(format, full, filename)
    Export::PeopleExportJob.new(
      format, current_person.id, person_filter,
      params.slice(:household).merge(full: full, filename: filename)
    ).enqueue!
  end

  def render_tabular(format, entries, full)
    exporter = Export::Tabular::People::Households if params[:household]
    exporter ||= full ? Export::Tabular::People::PeopleFull : Export::Tabular::People::PeopleAddress
    send_data exporter.export(format, entries), type: format
  end

  def render_entries_json(entries)
    render json: ListSerializer.new(prepare_entries(entries).
                                      includes(:social_accounts).
                                      decorate,
                                    group: @group,
                                    multiple_groups: @person_filter.multiple_groups,
                                    serializer: PeopleSerializer,
                                    controller: self)
  end

  def render_entry_json
    render json: PersonSerializer.new(entry.decorate, group: @group, controller: self)
  end

  def index_full_ability?
    if params[:range].blank? || params[:range] == 'group'
      can?(:index_full_people, @group)
    else
      can?(:index_deep_full_people, @group)
    end
  end
  public :index_full_ability? # for serializer
  hide_action :index_full_ability?

  def authorize_class
    authorize!(:index_people, group)
  end

  def validate_household
    household.valid?
  end

  def persist_household
    household.persist!
  end

  def household
    @household ||= Person::Household.new(entry, current_ability, nil, current_user)
  end

  def person_filter
    @person_filter ||= Person::Filter::List.new(@group, current_user, list_filter_args)
  end

end

app/controllers/person/colleagues_controller.rb
# encoding: utf-8

#  Copyright (c) 2017, Dachverband Schweizer Jugendparlamente. This file is
#  part of hitobito and licensed under the Affero General Public License
#  version 3 or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito.

class Person::ColleaguesController < ApplicationController

  before_action :authorize_action

  decorates :group, :person, :colleagues

  respond_to :html

  def index
    @colleagues = list_entries
    respond_with(@colleagues)
  end

  private

  def list_entries
    return Person.none.page(1) unless person.company_name?

    Person.
      where(company_name: person.company_name).
      preload_public_accounts.
      preload_groups.
      joins(:roles).
      order_by_name.
      distinct.
      page(params[:page])
  end

  def person
    @person ||= group.people.find(params[:id])
  end

  def group
    @group ||= Group.find(params[:group_id])
  end

  def authorize_action
    authorize!(:show, person)
  end

  def model_class
    Person
  end

  include Sortable

  self.sort_mappings = {
    roles: [Person.order_by_role_statement].concat(Person.order_by_name_statement)
  }

end

app/views/person/csv_imports/_description.html.haml
%h2=t('.header')

%p=t('.explain_csv_format')

%pre{style: 'padding-left: 1em;'}
  :preserve
    #{t('.example')}

%p=t('.explain_field_names')

%p=t('.explain_role')

%h3=t('.special_fields')

=t('.explain_special_fields_html')
%dl.dl-horizontal
  = csv_field_documentation(:gender, 'm' => t('global.gender.male'), 'w' => t('global.gender.female'))

  = render_extensions 'special_fields'

app/views/person/csv_imports/_hidden_form_fields.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

= hidden_field_tag :data, params[:data]
= hidden_field_tag :role_type, params[:role_type]
= hidden_field_tag :update_behaviour, params[:update_behaviour]

= fields_for :field_mappings do |f|
  - field_mappings.each do |key, value|
    = f.hidden_field key, value: value

app/views/person/csv_imports/_preview_table.html.haml
%div{style: 'max-height: 500px; margin-bottom: 20px; overflow: auto;'}
  = list_table do |t|
    - t.col('') do |p|
      - if p.errors.present?
        %i.icon.icon-warning-sign{title: t('.icon_tooltip_invalid')}
      - elsif @importer.request_people.include?(p)
        %i.icon.icon-question-sign{title: t('.icon_tooltip_request')}
      - elsif p.persisted?
        %i.icon.icon-refresh{title: t('.icon_tooltip_updated')}
      - else
        %i.icon.icon-plus{title: t('.icon_tooltip_created')}

    - t.attrs *csv_import_attrs

    - csv_import_contact_account_attrs do |account_attr|
      - t.col(account_attr[:value]) do |p|
        = csv_import_contact_account_value(p, account_attr[:key])

    - if field_mappings.values.include?('tags') && @can_manage_tags
      - t.col(ActsAsTaggableOn::Tag.model_name.human(count: 2)) do |p|
        = csv_import_tag_values(p)

app/views/person/csv_imports/define_mapping.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

= standard_form(:field_mappings, method: :post, url: preview_group_csv_imports_path, builder: PlainObjectFormBuilder) do |f|
  = hidden_field_tag :data, parser.to_csv

  = field_set_tag t('.update_behaviour') do
    %label.radio
      = radio_button_tag(:update_behaviour,
                         :keep,
                         params[:update_behaviour].blank? || params[:update_behaviour] == 'keep')
      = t('.keep_behaviour')
      - if @can_manage_tags
        = t('.keep_behaviour_tags')

    %label.radio
      = radio_button_tag(:update_behaviour,
                         :override,
                         params[:update_behaviour] == 'override')
      = t('.override_behaviour')
      - if @can_manage_tags
        = t('.override_behaviour_tags')

    %p.help-block= t('.update_behaviour_explanation')

  = field_set_tag t('.choose_role') do
    = f.labeled :role_type, Role.model_name.human do
      = select_tag(:role_type,
                   options_from_collection_for_select(@group.possible_roles, :sti_name, :label, @role_type),
                   { class: 'span4', prompt: I18n.t('helpers.select.prompt') })
      = f.help_block t('.choose_role_help')

  = field_set_tag t('.assign_columns_to_fields') do
    = f.labeled(nil, content_tag(:i, t('.column_from_csv'))) do
      %i{style: 'line-height: 30px'}= t('.field_in_database')
    %br/
    - parser.headers.each do |column_name|
      = f.labeled(column_name, column_name) do
        = f.collection_select(column_name,
                              application_person_fields,
                              :key,
                              :value,
                              { include_blank: true, selected: guess(column_name) },
                              { class: 'span4' })

  = save_form_buttons(f, t('.preview'), group_people_path(group))

app/views/person/csv_imports/new.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

#main.row-fluid
  .span5
    = standard_form(:csv_import, url: define_mapping_group_csv_imports_path, builder: PlainObjectFormBuilder) do |f|
      = save_form_buttons(f, t('.upload_button'), group_people_path(group))
      = f.labeled(:file, t('.csv_file')) do
        = f.file_field(:file)

  .span7
    .well.help
      = render 'description'

app/views/person/csv_imports/preview.html.haml
-#  Copyright (c) 2012-2013, Jungwacht Blauring Schweiz. This file is part of
-#  hitobito and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito.

%h3
  =t('.import_details_html', role: role_name, group: group)

= render 'preview_table'

= standard_form(:field_mappings, url: group_csv_imports_path, builder: PlainObjectFormBuilder) do |f|
  = render 'hidden_form_fields'
  .btn-toolbar
    .btn-group
      = f.submit(t('.import_now_button'), class: 'btn btn-primary')
    .btn-group
      = f.button(t('global.button.back'), class: 'btn btn-secondary', value: 'back')
    = link_to(t('global.button.cancel'), group_people_path(group), class: 'link')